name: Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.db_user }}
          POSTGRES_PASSWORD: ${{ env.db_password }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true
    - name: Install dependencies
      run: |
        gem install bundler
        bundler install
    - name: Run tests
      run: bundler exec rake
    
